### PR TITLE
[googlecompute] Add support for specifying 'labels' dict.

### PR DESCRIPTION
**Pull request by fatmcgav**
Ref https://www.packer.io/docs/builders/googlecompute.html#labels

### CODE REVIEW

**Comment by mayn** [comment]
thanks @fatmcgav

**Comment by fatmcgav** [comment]
Cheers for the merge @mayn ... Any chance of a new point release?

**Comment by mayn** [comment]
@fatmcgav done. https://github.com/mayn/packerlicious/releases/tag/v1.3.1

**Comment by fatmcgav** [comment]
Great, cheers @mayn :)

**Pull request merged**
