### PR TITLE
Add Inspec provsioner support

### PR DESCRIPTION
**Pull request by fatmcgav**
### List of Changes Proposed
Added support for the [Inspec](https://github.com/jrbeilke/packer-provisioner-inspec) Packer provisioner. 


### Testing Evidence
```
tox -e py27 -- tests/packerlicious/test_provisioner_inspec.py::TestInspecProvisioner::test_required_fields_missing
py27 develop-inst-noop: /Users/fatmcgav/Work/foss/packerlicious
py27 installed: atomicwrites==1.1.5,attrs==18.1.0,coverage==4.5.1,funcsigs==1.0.2,future==0.16.0,more-itertools==4.2.0,-e git+git@github.com:fatmcgav/packerlicious.git@00ecd8a7e06fb0dd259c046f968d5704e7ba8fd3#egg=packerlicious,pluggy==0.6.0,py==1.5.4,pytest==3.6.3,six==1.11.0
py27 runtests: PYTHONHASHSEED='3822679130'
py27 runtests: commands[0] | find . -type f -name '*.pyc' -delete
py27 runtests: commands[1] | find . -type d -name __pycache__ -delete
py27 runtests: commands[2] | /Users/fatmcgav/Work/foss/packerlicious/.tox/py27/bin/coverage erase
py27 runtests: commands[3] | /Users/fatmcgav/Work/foss/packerlicious/.tox/py27/bin/coverage run /Users/fatmcgav/Work/foss/packerlicious/.tox/py27/bin/pytest --basetemp=/Users/fatmcgav/Work/foss/packerlicious/.tox/py27/tmp tests/packerlicious/test_provisioner_inspec.py::TestInspecProvisioner::test_required_fields_missing
======================================================================================================================================================================== test session starts =========================================================================================================================================================================
platform darwin -- Python 2.7.15, pytest-3.6.3, py-1.5.4, pluggy-0.6.0 -- /Users/fatmcgav/Work/foss/packerlicious/.tox/py27/bin/python2.7
cachedir: .pytest_cache
rootdir: /Users/fatmcgav/Work/foss/packerlicious, inifile: setup.cfg
collected 1 item

tests/packerlicious/test_provisioner_inspec.py::TestInspecProvisioner::test_required_fields_missing PASSED                                                                                                                                                                                                                                                     [100%]

====================================================================================================================================================================== 1 passed in 0.19 seconds ======================================================================================================================================================================
py27 runtests: commands[4] | /Users/fatmcgav/Work/foss/packerlicious/.tox/py27/bin/coverage html -d /Users/fatmcgav/Work/foss/packerlicious/htmlcov/py27
______________________________________________________________________________________________________________________________________________________________________________ summary _______________________________________________________________________________________________________________________________________________________________________________
  py27: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by mayn** [comment]
thanks @fatmcgav , I'm going to sit on this for a few days while i think about the origination for community modules vs packer core.

**Comment by mayn** [comment]
Leaning towards putting them under a package called `community` Under packerlicious src. This way there is a logical separation, requiring explicit import by the user. `import community.post_processors` For example. Once imported, usage would remain the same. 
Thoughts?

**Comment by fatmcgav** [comment]
Sounds like a sensible enough approach...

**Comment by mayn** [comment]
@fatmcgav, moved code to `packerlicious.community.provisioner`. thanks for your contribution.

**Pull request merged**
