### PR TITLE
Install packer for CI

### LINKED ISSUE #63: install latest packer version as part of the setup for travis  / appveyor build environment
### Actual Behavior
functionality is being added that requires the presence of packer(https://packer.io) on our build system (see #27)

### Expected behavior
create an install.sh or equivalent (makefile?) for travisci and appveyor. This is to be used to install the latest packer installation.
In the future this may be expanded to test for compatibility across multiple packer versions.

### PR DESCRIPTION
**Pull request by fuzzmz**
### Issue
Fixes #63 

### List of Changes Proposed
Add a bash script which downloads the latest available version of Packer and unzips it.

### Testing Evidence
Not yet tested. Need to check if the CI environment has the tools required by the shell script.

### CODE REVIEW

**Comment by fuzzmz** [comment]
Strange, looks like GitHub doesn't want to see the change I did to [make the `get-packer.sh` script executable](https://github.com/fuzzmz/packerlicious/commit/40f00187e479b25e088782ec9b840d6966918275). Going to give it a bit more time, and if it still doesn't catch it we have two options:

1. close this PR and open a new one;
2. update the build configs to make the file executable there.

I'd honestly go with the first option, as it's cleaner than adding additional stuff in the build configs, but what do you say?

**Comment by fuzzmz** [comment]
OK, now we get packer on Travis CI in the build workspace.

Going to add a powershell script to download it for Appveyor tomorrow since at home I don't have access to a Windows machine.

**Comment by mayn** [comment]
@fuzzmz  this is awesome!
minor comment can we move these scripts to a `tools` folder when ready.

Thanks again.

**Comment by fuzzmz** [comment]
Sure thing.

**Comment by fuzzmz** [comment]
@mayn, any chance you can cancel the AppVeyor builds for this branch except for the "add debug messages" one? Looks like the powershell script fails somewhere and doesn't give any output, and it takes 1 hour for a job to timeout (and with 6 jobs per build, with another build queued which might not pass, it'll take ages to test this).

**Comment by mayn** [comment]
@fuzzmz done. I wonder if there is an appveyor setting you can inject into your branch to timeout faster?

**Comment by mayn** [comment]
@fuzzmz  http://help.appveyor.com/discussions/problems/62-how-do-i-increase-the-logging-level-for-the-deployment-log#comment_31002697

**Comment by fuzzmz** [comment]
Awesome, thanks!

**Comment by fuzzmz** [comment]
@mayn, can you also cancel these running builds? Have a final version tested it on my own instance of Appveyor which should be good to go.

Sorry for all the fuss, don't know why I didn't think of enabling integration with Appveyor with my own fork until now.

**Comment by fuzzmz** [comment]
OK, have to run from work so I'll push the final commits now. With this change everything seems to be working.

**Comment by fuzzmz** [comment]
This is pretty much done from my point of view. Any feedback?

**Comment by mayn** [comment]
@fuzzmz thanks. Will review/merge later today

**Pull request merged**
